### ISSUE TITLE
New release for Twitter Bootstrap 3.0

### ISSUE THREAD

**Issue by erral** [collective/collective.js.bootstrap#2]
@toutpt can you release collective.js.bootstrap both for 2.3.2 version and 3.0.3?

Thanks,

Mikel

**Comment by tomgross** [comment]
Meanwhile the current version is 3.3.1: https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip

**Comment by erral** [comment]
@toutpt please, add @tomgross and me as package owners on PyPi

**Comment by petri** [comment]
+1, please release

**Comment by erral** [comment]
@ebrehault already made the release
