### ISSUE TITLE
Release 3.3.4 please

### ISSUE THREAD

**Issue by erral** [collective/collective.js.bootstrap#4]
@ebrehault can you release 3.3.4 version please? I have also added the 3.3.2 version

**Comment by hvelarde** [comment]
@ebrehault do you mind adding more people as maintainers on PyPI?

**Comment by ebrehault** [comment]
Oops, sorry, done.
@erral sorry I haven't seen your demand last june.
@hvelarde I have added you as owner of the package, @erral I can add you too, just tell me your Pypi id.

**Comment by erral** [comment]
It's erral.

Thx.

On Wed, Nov 4, 2015 at 8:10 PM, Eric BREHAULT <notifications@github.com>
wrote:

> Oops, sorry, done.
> @erral <https://github.com/erral> sorry I haven't seen your demand last
> june.
> @hvelarde <https://github.com/hvelarde> I have added you as owner of the
> package, @erral <https://github.com/erral> I can add you too, just tell
> me your Pypi id.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/collective/collective.js.bootstrap/issues/4#issuecomment-153833692>
> .
>



-- 
Mikel Larreategi
mlarreategi@codesyntax.com

CodeSyntax
Azitaingo Industrialdea 3 K
E-20600 Eibar
Tel: (+34) 943 82 17 80

**Comment by ebrehault** [comment]
@erral ok you're owner too now!

**Comment by erral** [comment]
I just released 3.3.5 too.
